# Generated by Django 4.2.16 on 2024-12-17 08:30

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Commit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="max 150 символов",
                        max_length=150,
                        validators=[
                            django.core.validators.MinLengthValidator(2)
                        ],
                        verbose_name="название",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
            ],
            options={
                "verbose_name": "коммит",
                "verbose_name_plural": "коммиты",
            },
        ),
        migrations.CreateModel(
            name="Repository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="max 150 символов",
                        max_length=150,
                        validators=[
                            django.core.validators.MinLengthValidator(2)
                        ],
                        verbose_name="название",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, verbose_name="опубликовано"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "verbose_name": "репозиторий",
                "verbose_name_plural": "репозитории",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="max 150 символов",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(2)
                        ],
                        verbose_name="название",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, verbose_name="опубликовано"
                    ),
                ),
            ],
            options={
                "verbose_name": "тег",
                "verbose_name_plural": "теги",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="max 150 символов",
                        max_length=150,
                        validators=[
                            django.core.validators.MinLengthValidator(2)
                        ],
                        verbose_name="название",
                    ),
                ),
                (
                    "text",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        help_text="Вспомогательный текст", verbose_name="текст"
                    ),
                ),
                ("start_at", models.DateField(null=True)),
                ("end_at", models.DateField(null=True)),
                (
                    "commit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="repositories.commit",
                        verbose_name="коммит",
                    ),
                ),
                (
                    "first_commit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="first_commit",
                        to="repositories.commit",
                        verbose_name="первый комит",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        to="repositories.tag", verbose_name="теги"
                    ),
                ),
            ],
            options={
                "verbose_name": "задача",
                "verbose_name_plural": "задачи",
            },
        ),
    ]
