# Generated by Django 4.2.16 on 2024-12-18 19:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="attempts_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="blocked_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
