# Generated by Django 4.2.16 on 2024-12-20 12:39

import apps.users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_attempts_count_user_blocked_time"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.users.models.Manager()),
            ],
        ),
    ]
